import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';

const SECTIONS = [
    { title: 'Acceptance of Terms', body: 'By accessing or using StyleSync ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. We may update these terms from time to time and will notify you of material changes via email or in-app notification.' },
    { title: 'Use of the Service', body: 'StyleSync is an AI-powered personal styling platform. You may use the Service for lawful, personal, non-commercial purposes only. You agree not to misuse the Service, attempt to reverse-engineer any component, or use the Service in a way that could harm other users or the platform.' },
    { title: 'User Accounts', body: 'You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must be at least 13 years old to use StyleSync. Please notify us immediately of any unauthorized use of your account.' },
    { title: 'AI-Generated Content', body: 'Style DNA reports, outfit recommendations, and virtual try-on results are generated by AI and are intended as suggestions only. StyleSync makes no warranty that AI recommendations will be accurate, complete, or suitable for any particular purpose. Use your own judgment when making fashion decisions.' },
    { title: 'Image & Data Processing', body: 'When you use our body scan feature, camera images are processed locally in your browser using MediaPipe. No raw camera footage is stored on our servers. Processed measurements and scan confidence scores may be temporarily stored to generate your Style DNA report.' },
    { title: 'Intellectual Property', body: 'All content on StyleSync — including the design, editorial content, AI models, and code — is the intellectual property of StyleSync and its licensors. You may not reproduce, distribute, or create derivative works without our explicit written permission.' },
    { title: 'Limitation of Liability', body: 'StyleSync and its affiliates shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to lost profits, data loss, or any harm resulting from reliance on AI-generated styling recommendations.' },
    { title: 'Termination', body: 'We reserve the right to suspend or terminate your account at our discretion if you violate these Terms of Service. You may also delete your account at any time from your profile settings. Upon termination, your data will be handled per our Privacy Policy.' },
    { title: 'Governing Law', body: 'These Terms shall be governed by the laws of the jurisdiction in which StyleSync operates, without regard to conflict of law principles. Any disputes will be resolved through binding arbitration, except where prohibited by law.' },
    { title: 'Contact', body: 'If you have questions about these Terms, please contact us at legal@stylesync.ai.' },
];

export default function Terms() {
    return (
        <div style={{ minHeight: '100vh', background: 'var(--color-bg)', color: 'var(--color-text)', fontFamily: '"DM Sans", sans-serif' }}>
            <main style={{ maxWidth: 760, margin: '0 auto', padding: 'calc(var(--navbar-height) + 60px) 32px 100px' }}>

                {/* Back */}
                <Link to="/signup" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--color-muted)', textDecoration: 'none', marginBottom: 48 }}
                    onMouseEnter={e => e.currentTarget.style.color = 'var(--color-accent)'}
                    onMouseLeave={e => e.currentTarget.style.color = 'var(--color-muted)'}
                >
                    <span className="material-icons" style={{ fontSize: 14 }}>arrow_back</span>
                    Back
                </Link>

                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }}>
                    <span className="label-accent" style={{ display: 'block', marginBottom: 12 }}>Legal</span>
                    <h1 style={{ fontFamily: '"Cormorant Garamond", Georgia, serif', fontSize: 'clamp(36px, 4vw, 52px)', fontWeight: 400, fontStyle: 'italic', margin: '0 0 12px', lineHeight: 1.1 }}>
                        Terms of Service
                    </h1>
                    <p style={{ fontSize: 13, color: 'var(--color-muted)', margin: '0 0 60px' }}>Last updated: April 2026</p>

                    <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
                        {SECTIONS.map((s, i) => (
                            <motion.div
                                key={s.title}
                                initial={{ opacity: 0, y: 16 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ delay: i * 0.05, duration: 0.4 }}
                            >
                                <h2 style={{ fontFamily: '"DM Sans", sans-serif', fontSize: 15, fontWeight: 700, color: 'var(--color-text)', margin: '0 0 10px', letterSpacing: '0.01em' }}>
                                    {i + 1}. {s.title}
                                </h2>
                                <p style={{ fontSize: 14, color: 'var(--color-muted)', lineHeight: 1.8, margin: 0 }}>{s.body}</p>
                            </motion.div>
                        ))}
                    </div>
                </motion.div>
            </main>
        </div>
    );
}
